version: '3.9'

services:
  postgres:
    container_name: winphim_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: winphim
      POSTGRES_PASSWORD: winphim_password
      POSTGRES_DB: winphim_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: winphim_redis
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "redis123"]
    environment:
      REDIS_PASSWORD: redis123
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
